CREATE SEQUENCE PUBLIC.PERSONNE_MATCH_SEQ START WITH 640850 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.MATCH_SEQ START WITH 13750 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.BENEVOLAT_SEQ START WITH 10013;

CREATE SEQUENCE PUBLIC.PERSONNE_COTISATION_SEQ START WITH 32500 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.TEAM_SEASON_SEQ START WITH 4100 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.PERSON_SEQ START WITH 10013800 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.ACCOUNTING_SEQ START WITH 3956;

CREATE SEQUENCE PUBLIC.PRICES_SEQ START WITH 13191;

CREATE SEQUENCE PUBLIC.TEAM_SEQ START WITH 10300 INCREMENT BY 50;

CREATE SEQUENCE PUBLIC.TRAVEL_PRICE_SEQ START WITH 100033;

CREATE SEQUENCE PUBLIC.ABONNEMENT_SEQ START WITH 2011400 INCREMENT BY 50;

CREATE TABLE PUBLIC.MATCH(
    MATCH_ID DECIMAL(10) NOT NULL,
    PLACE VARCHAR(50) NOT NULL,
    DATE_MATCH TIMESTAMP,
    SAISON_EQUIPE_ID DECIMAL(0),
    OPPONENT NUMBER,
    SAISON_ID VARCHAR(10),
    COMPETITION_TYPE VARCHAR(16),
    MATCH_TYPE VARCHAR(19),
    PRICE_TYPE VARCHAR(6)
);

ALTER TABLE PUBLIC.MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(MATCH_ID);

CREATE TABLE PUBLIC.PERSONNE_MATCH(
    MATCH_ID DECIMAL(10) NOT NULL,
    PERSONNE_ID DECIMAL(10) NOT NULL,
    PRIX_LOCOMOTION_ID DECIMAL(10),
    CAR_TRAVEL_AMOUNT INT,
    ID BIGINT NOT NULL
);

ALTER TABLE PUBLIC.PERSONNE_MATCH ADD CONSTRAINT PUBLIC.PERSONNES_MATCH_PK PRIMARY KEY(ID);

CREATE TABLE PUBLIC.BENEVOLAT(
    BENEVOLAT_ID DECIMAL(0) NOT NULL,
    PERSONNE_ID DECIMAL(0),
    MONTANT DECIMAL(0),
    TYPE_BENEVOLAT VARCHAR(100),
    DATE_BENEVOLAT TIMESTAMP
);

ALTER TABLE PUBLIC.BENEVOLAT ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(BENEVOLAT_ID);

CREATE TABLE PUBLIC.BLOC(
    BLOC_VALUE VARCHAR(50) NOT NULL,
    TRIBUNE VARCHAR(100),
    CLUB VARCHAR(200) NOT NULL,
    BLOC_ID DECIMAL(0) NOT NULL,
    EQUIPE_ID DECIMAL(0)
);

ALTER TABLE PUBLIC.BLOC ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(BLOC_ID);

CREATE TABLE PUBLIC.COMMANDE_PLACE(
    COMMANDE_PLACE_ID DECIMAL(10) NOT NULL,
    PERSONNE_ID DECIMAL(10) NOT NULL,
    MATCH_ID DECIMAL(10) NOT NULL,
    DATE_COMMANDE TIMESTAMP NOT NULL,
    NOMBRE_PLACE DECIMAL(3) NOT NULL,
    TYPE_PLACE VARCHAR(4000),
    BLOC_ID DECIMAL(0),
    PLACE_COMMANDEE DECIMAL(1) NOT NULL
);

ALTER TABLE PUBLIC.COMMANDE_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(COMMANDE_PLACE_ID);

CREATE TABLE PUBLIC.COTISATIONS(
    ANNEE_COTISATION VARCHAR(4),
    MONTANT_COTISATION DECIMAL(10, 2) NOT NULL,
    ANNEE_COTISATION2 DECIMAL(4) NOT NULL
);

ALTER TABLE PUBLIC.COTISATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ANNEE_COTISATION2);

CREATE TABLE PUBLIC.EQUIPE(
    EQUIPE_ID DECIMAL(0) NOT NULL,
    NOM_EQUIPE VARCHAR(150) NOT NULL
);

ALTER TABLE PUBLIC.EQUIPE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(EQUIPE_ID);

CREATE TABLE PUBLIC.PRIX_PLACE(
    PRIX_PLACE_ID DECIMAL(10) NOT NULL,
    BLOC_ID VARCHAR(100) NOT NULL,
    TYPE_PERSONNE_ID DECIMAL(10) NOT NULL,
    TYPE_MATCH_ID DECIMAL(10) NOT NULL,
    MONTANT DECIMAL(10) NOT NULL,
    SAISON VARCHAR(10) NOT NULL,
    TARIF DECIMAL(1),
    ABONNE DECIMAL(1)
);

ALTER TABLE PUBLIC.PRIX_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_49 PRIMARY KEY(PRIX_PLACE_ID);

CREATE TABLE PUBLIC.PRICES(
    ID NUMERIC NOT NULL,
    SAISON_ID VARCHAR(10) NOT NULL,
    PRIX NUMERIC NOT NULL,
    TRIBUNE NUMERIC,
    BLOC VARCHAR(5),
    TYPE_PERSONNE VARCHAR(16) NOT NULL,
    TYPE_COMPETITION VARCHAR(16) NOT NULL,
    RANG NUMERIC,
    PLACE NUMERIC,
    PRICE_TYPE VARCHAR(20)
);

ALTER TABLE PUBLIC.PRICES ADD CONSTRAINT PUBLIC.PRICES_PK PRIMARY KEY(ID);

CREATE TABLE PUBLIC.SAISON_EQUIPE(
    SAISON_ID VARCHAR(10) NOT NULL,
    SAISON_EQUIPE_ID DECIMAL(0) NOT NULL,
    EQUIPE_ID DECIMAL(0) NOT NULL
);

ALTER TABLE PUBLIC.SAISON_EQUIPE ADD CONSTRAINT PUBLIC.CONSTRAINT_75 PRIMARY KEY(SAISON_EQUIPE_ID);

CREATE TABLE PUBLIC.TYPE_COMPETITION(
    TYPE_COMPETITION_ID DECIMAL(4) NOT NULL,
    TYPE_COMPETITION_VALUE VARCHAR(100) NOT NULL
);

ALTER TABLE PUBLIC.TYPE_COMPETITION ADD CONSTRAINT PUBLIC.CONSTRAINT_39 PRIMARY KEY(TYPE_COMPETITION_ID);

CREATE TABLE PUBLIC.TYPE_MATCH(
    TYPE_MATCH_ID DECIMAL(4) NOT NULL,
    TYPE_COMPETITION_ID DECIMAL(0) NOT NULL,
    DENOMINATION_MATCH VARCHAR(100) NOT NULL
);

ALTER TABLE PUBLIC.TYPE_MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_12 PRIMARY KEY(TYPE_MATCH_ID);

CREATE TABLE PUBLIC.TYPE_PERSONNE(
    TYPE_PERSONNE_ID DECIMAL(4) NOT NULL,
    DENOMINATION_TYPE_PERSONNE VARCHAR(100) NOT NULL,
    AGE_MINIMUM DECIMAL(2),
    AGE_MAXIMUM DECIMAL(3),
    ETUDIANT DECIMAL(1),
    MEMBRE DECIMAL(1),
    TARIF DECIMAL(2)
);

ALTER TABLE PUBLIC.TYPE_PERSONNE ADD CONSTRAINT PUBLIC.CONSTRAINT_9D PRIMARY KEY(TYPE_PERSONNE_ID);

CREATE TABLE PUBLIC.ABONNEMENT(
    ABONNEMENT_ID DECIMAL(10) NOT NULL,
    PERSONNE_ID DECIMAL(10) NOT NULL,
    PLACE VARCHAR(100),
    SAISON VARCHAR(10) NOT NULL,
    REDUCTION DECIMAL(10) NOT NULL,
    PAYE DECIMAL(1) NOT NULL,
    BLOC_ID DECIMAL(0),
    RANG VARCHAR(6),
    ACOMPTE DECIMAL(0),
    ABONNEMENT_STATUS VARCHAR(20),
    PRICES_ID BIGINT,
    BLOC_VALUE VARCHAR(3)
);

ALTER TABLE PUBLIC.ABONNEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ABONNEMENT_ID);

CREATE TABLE PUBLIC.SAISON(
    SAISON_ID VARCHAR(10) NOT NULL,
    DATE_DEBUT TIMESTAMP NOT NULL,
    DATE_FIN TIMESTAMP NOT NULL,
    DATE_PREMIER_MATCH_CHAMPIONNAT TIMESTAMP,
    EUROPEENS DECIMAL(1),
    MONTANT_COTISATION NUMBER
);

ALTER TABLE PUBLIC.SAISON ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(SAISON_ID);

CREATE TABLE PUBLIC.TRAVEL_PRICE(
    ID DECIMAL(10) NOT NULL,
    MONTANT DECIMAL(10, 2) NOT NULL,
    TYPE_PERSONNE VARCHAR(50),
    PLACE VARCHAR(20) NOT NULL,
    MEMBRE DECIMAL(1) NOT NULL,
    SEASON_ID VARCHAR(10)
);

ALTER TABLE PUBLIC.TRAVEL_PRICE ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);

CREATE TABLE PUBLIC.PERSONNES_COTISATIONS(
    PERSONNE_ID DECIMAL(10) NOT NULL,
    ANNEE_COTISATION VARCHAR(4),
    DATE_PAIEMENT TIMESTAMP,
    CARTE_MEMBRE_ENVOYEE DECIMAL(0),
    SEASON_ID VARCHAR(10),
    ID BIGINT NOT NULL
);

ALTER TABLE PUBLIC.PERSONNES_COTISATIONS ADD CONSTRAINT PUBLIC.PERSONNES_COTISATIONS_PK PRIMARY KEY(ID);

CREATE TABLE PUBLIC.ACCOUNTING(
    ID NUMERIC NOT NULL,
    ACCOUNTING_DATE DATE,
    DESCRIPTION VARCHAR(256),
    TYPE VARCHAR(5),
    AMOUNT DECIMAL
);

ALTER TABLE PUBLIC.ACCOUNTING ADD CONSTRAINT PUBLIC.ACCOUNTING_PK PRIMARY KEY(ID);

CREATE TABLE PUBLIC.PERSONNES(
    PERSONNE_ID DECIMAL(10) NOT NULL,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    ADRESSE VARCHAR(200),
    CODE_POSTAL VARCHAR(10),
    VILLE VARCHAR(200),
    TELEPHONE VARCHAR(20),
    GSM VARCHAR(15),
    EMAIL VARCHAR(150),
    DATE_NAISSANCE TIMESTAMP,
    NUMERO_MEMBRE DECIMAL(10),
    CARTE_IDENTITE VARCHAR(20),
    ETUDIANT DECIMAL(1),
    VALIDITE_CARTE_IDENTITE TIMESTAMP,
    RED_CARD BOOLEAN DEFAULT 'false',
    CUS VARCHAR(50)
);

ALTER TABLE PUBLIC.PERSONNES ADD CONSTRAINT PUBLIC.CONSTRAINT_D8 PRIMARY KEY(PERSONNE_ID);

ALTER TABLE PUBLIC.PRIX_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_49E FOREIGN KEY(SAISON) REFERENCES PUBLIC.SAISON(SAISON_ID) NOCHECK;

ALTER TABLE PUBLIC.TRAVEL_PRICE ADD CONSTRAINT PUBLIC.TRAVEL_PRICE_SEASON_FK FOREIGN KEY(SEASON_ID) REFERENCES PUBLIC.SAISON(SAISON_ID) NOCHECK;

ALTER TABLE PUBLIC.COMMANDE_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_84B7 FOREIGN KEY(PERSONNE_ID) REFERENCES PUBLIC.PERSONNES(PERSONNE_ID) NOCHECK;

ALTER TABLE PUBLIC.PRICES ADD CONSTRAINT PUBLIC.PRICES_SEASON_FK FOREIGN KEY(SAISON_ID) REFERENCES PUBLIC.SAISON(SAISON_ID) NOCHECK;

ALTER TABLE PUBLIC.MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_45 FOREIGN KEY(SAISON_EQUIPE_ID) REFERENCES PUBLIC.SAISON_EQUIPE(SAISON_EQUIPE_ID) NOCHECK;

ALTER TABLE PUBLIC.PERSONNES_COTISATIONS ADD CONSTRAINT PUBLIC.CONSTRAINT_44 FOREIGN KEY(PERSONNE_ID) REFERENCES PUBLIC.PERSONNES(PERSONNE_ID) NOCHECK;

ALTER TABLE PUBLIC.PERSONNE_MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_3485 FOREIGN KEY(PERSONNE_ID) REFERENCES PUBLIC.PERSONNES(PERSONNE_ID) NOCHECK;

ALTER TABLE PUBLIC.COMMANDE_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_84B FOREIGN KEY(BLOC_ID) REFERENCES PUBLIC.BLOC(BLOC_ID) NOCHECK;

ALTER TABLE PUBLIC.PERSONNES_COTISATIONS ADD CONSTRAINT PUBLIC.PERSONNES_COTISATIONS_SEASON_FK FOREIGN KEY(SEASON_ID) REFERENCES PUBLIC.SAISON(SAISON_ID) NOCHECK;

ALTER TABLE PUBLIC.ABONNEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F5F7 FOREIGN KEY(BLOC_ID) REFERENCES PUBLIC.BLOC(BLOC_ID) NOCHECK;

ALTER TABLE PUBLIC.PERSONNE_MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_34854 FOREIGN KEY(MATCH_ID) REFERENCES PUBLIC.MATCH(MATCH_ID) NOCHECK;

ALTER TABLE PUBLIC.ABONNEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F5F FOREIGN KEY(SAISON) REFERENCES PUBLIC.SAISON(SAISON_ID) NOCHECK;

ALTER TABLE PUBLIC.PERSONNE_MATCH ADD CONSTRAINT PUBLIC.CONSTRAINT_348 FOREIGN KEY(PRIX_LOCOMOTION_ID) REFERENCES PUBLIC.TRAVEL_PRICE(ID) NOCHECK;

ALTER TABLE PUBLIC.PRIX_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_49E0 FOREIGN KEY(TYPE_MATCH_ID) REFERENCES PUBLIC.TYPE_MATCH(TYPE_MATCH_ID) NOCHECK;

ALTER TABLE PUBLIC.ABONNEMENT ADD CONSTRAINT PUBLIC.ABONNEMENT_PRICES_FK FOREIGN KEY(PRICES_ID) REFERENCES PUBLIC.PRICES(ID) NOCHECK;

ALTER TABLE PUBLIC.COMMANDE_PLACE ADD CONSTRAINT PUBLIC.CONSTRAINT_84 FOREIGN KEY(MATCH_ID) REFERENCES PUBLIC.MATCH(MATCH_ID) NOCHECK;

ALTER TABLE PUBLIC.ABONNEMENT ADD CONSTRAINT PUBLIC.CONSTRAINT_F5 FOREIGN KEY(PERSONNE_ID) REFERENCES PUBLIC.PERSONNES(PERSONNE_ID) NOCHECK;

ALTER TABLE PUBLIC.BENEVOLAT ADD CONSTRAINT PUBLIC.CONSTRAINT_D2 FOREIGN KEY(PERSONNE_ID) REFERENCES PUBLIC.PERSONNES(PERSONNE_ID) NOCHECK;
