-- Sequences
CREATE SEQUENCE IF NOT EXISTS PERSONNE_MATCH_SEQ START WITH 640850 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS MATCH_SEQ START WITH 13750 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS BENEVOLAT_SEQ START WITH 10013 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PERSONNE_COTISATION_SEQ START WITH 32500 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS TEAM_SEASON_SEQ START WITH 4100 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS PERSON_SEQ START WITH 10013800 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS ACCOUNTING_SEQ START WITH 3956 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRICES_SEQ START WITH 13191 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TEAM_SEQ START WITH 10300 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS TRAVEL_PRICE_SEQ START WITH 100033 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ABONNEMENT_SEQ START WITH 2011400 INCREMENT BY 1;

-- Base Tables
CREATE TABLE IF NOT EXISTS SAISON (
    SAISON_ID VARCHAR(10) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    DATE_PREMIER_MATCH_CHAMPIONNAT DATE,
    EUROPEENS BOOLEAN,
    MONTANT_COTISATION NUMERIC(19, 2),
    CONSTRAINT PK_SAISON PRIMARY KEY (SAISON_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPE (
    EQUIPE_ID BIGINT NOT NULL,
    NOM_EQUIPE VARCHAR(150) NOT NULL,
    CONSTRAINT PK_EQUIPE PRIMARY KEY (EQUIPE_ID)
);

CREATE TABLE IF NOT EXISTS COTISATIONS (
    ANNEE_COTISATION2 BIGINT NOT NULL,
    ANNEE_COTISATION VARCHAR(4),
    MONTANT_COTISATION NUMERIC(10, 2) NOT NULL,
    CONSTRAINT PK_COTISATIONS PRIMARY KEY (ANNEE_COTISATION2)
);

CREATE TABLE IF NOT EXISTS ACCOUNTING (
    ID BIGINT NOT NULL,
    ACCOUNTING_DATE DATE,
    DESCRIPTION VARCHAR(256),
    TYPE VARCHAR(5),
    AMOUNT NUMERIC(19, 2),
    CONSTRAINT PK_ACCOUNTING PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PERSONNES (
    PERSONNE_ID BIGINT NOT NULL,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100),
    ADRESSE VARCHAR(200),
    CODE_POSTAL VARCHAR(10),
    VILLE VARCHAR(100),
    TELEPHONE VARCHAR(20),
    GSM VARCHAR(20),
    EMAIL VARCHAR(120),
    DATE_NAISSANCE DATE,
    NUMERO_MEMBRE BIGINT,
    CARTE_IDENTITE VARCHAR(50),
    ETUDIANT BOOLEAN,
    VALIDITE_CARTE_IDENTITE DATE,
    RED_CARD BOOLEAN DEFAULT FALSE,
    CUS VARCHAR(50),
    CONSTRAINT PK_PERSONNES PRIMARY KEY (PERSONNE_ID)
);

CREATE TABLE IF NOT EXISTS SAISON_EQUIPE (
    SAISON_EQUIPE_ID BIGINT NOT NULL,
    SAISON_ID VARCHAR(10) NOT NULL,
    EQUIPE_ID BIGINT NOT NULL,
    CONSTRAINT PK_SAISON_EQUIPE PRIMARY KEY (SAISON_EQUIPE_ID)
);

CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT NOT NULL,
    SAISON_ID VARCHAR(10) NOT NULL,
    PRIX BIGINT NOT NULL,
    TRIBUNE INT,
    BLOC VARCHAR(50) NOT NULL,
    TYPE_PERSONNE VARCHAR(50),
    TYPE_COMPETITION VARCHAR(50) NOT NULL,
    RANG VARCHAR(50),
    PLACE VARCHAR(50),
    PRICE_TYPE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_PRICES PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TRAVEL_PRICE (
    ID BIGINT NOT NULL,
    SEASON_ID VARCHAR(10),
    MONTANT NUMERIC(19, 2) NOT NULL,
    PLACE VARCHAR(50) NOT NULL,
    MEMBRE BOOLEAN NOT NULL,
    TYPE_PERSONNE VARCHAR(50),
    CONSTRAINT PK_TRAVEL_PRICE PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS BENEVOLAT (
    BENEVOLAT_ID BIGINT NOT NULL,
    PERSONNE_ID BIGINT NOT NULL,
    MONTANT NUMERIC(19, 2),
    TYPE_BENEVOLAT VARCHAR(100),
    DATE_BENEVOLAT DATE,
    CONSTRAINT PK_BENEVOLAT PRIMARY KEY (BENEVOLAT_ID)
);

CREATE TABLE IF NOT EXISTS PERSONNES_COTISATIONS (
    ID BIGINT NOT NULL,
    PERSONNE_ID BIGINT NOT NULL,
    SEASON_ID VARCHAR(10) NOT NULL,
    DATE_PAIEMENT DATE,
    CARTE_MEMBRE_ENVOYEE BOOLEAN NOT NULL DEFAULT FALSE,
    ANNEE_COTISATION VARCHAR(4),
    CONSTRAINT PK_PERSONNES_COTISATIONS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MATCH (
    MATCH_ID BIGINT NOT NULL,
    SAISON_ID VARCHAR(10) NOT NULL,
    OPPONENT BIGINT NOT NULL,
    SAISON_EQUIPE_ID BIGINT,
    DATE_MATCH TIMESTAMP,
    PLACE VARCHAR(50) NOT NULL,
    COMPETITION_TYPE VARCHAR(16) NOT NULL,
    MATCH_TYPE VARCHAR(19),
    PRICE_TYPE VARCHAR(6),
    CONSTRAINT PK_MATCH PRIMARY KEY (MATCH_ID)
);

CREATE TABLE IF NOT EXISTS PERSONNE_MATCH (
    ID BIGINT NOT NULL,
    PERSONNE_ID BIGINT NOT NULL,
    MATCH_ID BIGINT NOT NULL,
    CAR_TRAVEL_AMOUNT BIGINT NOT NULL,
    PRIX_LOCOMOTION_ID BIGINT,
    CONSTRAINT PK_PERSONNE_MATCH PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ABONNEMENT (
    ABONNEMENT_ID BIGINT NOT NULL,
    PERSONNE_ID BIGINT,
    SAISON VARCHAR(10) NOT NULL,
    PRICES_ID BIGINT,
    RANG VARCHAR(6),
    PLACE VARCHAR(100),
    REDUCTION BIGINT NOT NULL,
    PAYE BOOLEAN NOT NULL,
    ACOMPTE BIGINT,
    ABONNEMENT_STATUS VARCHAR(20),
    BLOC_VALUE VARCHAR(50),
    BLOC_ID BIGINT,
    CONSTRAINT PK_ABONNEMENT PRIMARY KEY (ABONNEMENT_ID)
);

-- Legacy Tables (for historical reference and backup compatibility)
CREATE TABLE IF NOT EXISTS BLOC (
    BLOC_ID BIGINT NOT NULL,
    BLOC_VALUE VARCHAR(50) NOT NULL,
    TRIBUNE VARCHAR(100),
    CLUB VARCHAR(200) NOT NULL,
    EQUIPE_ID BIGINT,
    CONSTRAINT PK_BLOC PRIMARY KEY (BLOC_ID)
);

CREATE TABLE IF NOT EXISTS COMMANDE_PLACE (
    COMMANDE_PLACE_ID BIGINT NOT NULL,
    PERSONNE_ID BIGINT NOT NULL,
    MATCH_ID BIGINT NOT NULL,
    DATE_COMMANDE TIMESTAMP NOT NULL,
    NOMBRE_PLACE INT NOT NULL,
    TYPE_PLACE VARCHAR(4000),
    BLOC_ID BIGINT,
    PLACE_COMMANDEE INT NOT NULL,
    CONSTRAINT PK_COMMANDE_PLACE PRIMARY KEY (COMMANDE_PLACE_ID)
);

CREATE TABLE IF NOT EXISTS PRIX_PLACE (
    PRIX_PLACE_ID BIGINT NOT NULL,
    BLOC_ID VARCHAR(100) NOT NULL,
    TYPE_PERSONNE_ID BIGINT NOT NULL,
    TYPE_MATCH_ID BIGINT NOT NULL,
    MONTANT NUMERIC NOT NULL,
    SAISON VARCHAR(10) NOT NULL,
    TARIF NUMERIC,
    ABONNE NUMERIC,
    CONSTRAINT PK_PRIX_PLACE PRIMARY KEY (PRIX_PLACE_ID)
);

CREATE TABLE IF NOT EXISTS TYPE_COMPETITION (
    TYPE_COMPETITION_ID BIGINT NOT NULL,
    TYPE_COMPETITION_VALUE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TYPE_COMPETITION PRIMARY KEY (TYPE_COMPETITION_ID)
);

CREATE TABLE IF NOT EXISTS TYPE_MATCH (
    TYPE_MATCH_ID BIGINT NOT NULL,
    TYPE_COMPETITION_ID BIGINT NOT NULL,
    DENOMINATION_MATCH VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TYPE_MATCH PRIMARY KEY (TYPE_MATCH_ID)
);

CREATE TABLE IF NOT EXISTS TYPE_PERSONNE (
    TYPE_PERSONNE_ID BIGINT NOT NULL,
    DENOMINATION_TYPE_PERSONNE VARCHAR(100) NOT NULL,
    AGE_MINIMUM INT,
    AGE_MAXIMUM INT,
    ETUDIANT INT,
    MEMBRE INT,
    TARIF INT,
    CONSTRAINT PK_TYPE_PERSONNE PRIMARY KEY (TYPE_PERSONNE_ID)
);
