/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package standardNaast.viewNew;

import java.awt.Container;
import java.util.ResourceBundle;

import javax.swing.GroupLayout;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.WindowConstants;

import standardNaast.viewNew.members.MembersForm;
import standardNaast.viewNew.members.MembersTable;

/**
 * 
 * @author stessy
 */
public class StandardNaastFrame extends javax.swing.JFrame {

	/** The serialVersionUID. */
	private static final long serialVersionUID = -375071960070249000L;


	/**
	 * Creates new form StandardNaastFrame
	 */
	public StandardNaastFrame() {
		this.initComponents();
		this.initializeObserver();
	}


	private void initializeObserver() {
		this.membersTable.registerObserver(this.membersForm);

	}


	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
			private
			void initComponents() {
		ResourceBundle bundle = ResourceBundle.getBundle("Bundle");
		this.jMenuBar1 = new JMenuBar();
		this.jMenu1 = new JMenu();
		this.jMenu2 = new JMenu();
		this.mainTabbedPane = new JTabbedPane();
		this.memberTabbedPane = new JTabbedPane();
		this.membersTable = new MembersTable();
		this.jPanel1 = new JPanel();
		this.membersForm = new MembersForm();

		// ======== this ========
		this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		Container contentPane = this.getContentPane();

		// ======== jMenuBar1 ========
		{

			// ======== jMenu1 ========
			{
				this.jMenu1.setText("File");
			}
			this.jMenuBar1.add(this.jMenu1);

			// ======== jMenu2 ========
			{
				this.jMenu2.setText("Edit");
			}
			this.jMenuBar1.add(this.jMenu2);
		}
		this.setJMenuBar(this.jMenuBar1);

		// ======== mainTabbedPane ========
		{

			// ======== memberTabbedPane ========
			{
				this.memberTabbedPane.addTab(bundle.getString("member.tabbedPane.listMember.title"), this.membersTable);

				// ======== jPanel1 ========
				{

					GroupLayout jPanel1Layout = new GroupLayout(this.jPanel1);
					this.jPanel1.setLayout(jPanel1Layout);
					jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup().addGroup(
							jPanel1Layout.createSequentialGroup().addContainerGap()
									.addComponent(this.membersForm, GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
									.addContainerGap()));
					jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup().addGroup(
							jPanel1Layout.createSequentialGroup().addContainerGap()
									.addComponent(this.membersForm, GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
									.addContainerGap()));
				}
				this.memberTabbedPane.addTab(bundle.getString("member.detailPanel.title"), this.jPanel1);
			}
			this.mainTabbedPane.addTab(bundle.getString("main.tabbedPane.member.title"), this.memberTabbedPane);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(contentPaneLayout
				.createParallelGroup()
				.addGroup(
						contentPaneLayout.createParallelGroup().addComponent(this.mainTabbedPane,
								GroupLayout.Alignment.TRAILING)).addGap(0, 733, Short.MAX_VALUE));
		contentPaneLayout.setVerticalGroup(contentPaneLayout
				.createParallelGroup()
				.addGroup(
						contentPaneLayout.createParallelGroup().addComponent(this.mainTabbedPane,
								GroupLayout.Alignment.TRAILING)).addGap(0, 472, Short.MAX_VALUE));
		this.pack();
		this.setLocationRelativeTo(this.getOwner());
	}// </editor-fold>//GEN-END:initComponents


	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StandardNaastFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StandardNaastFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StandardNaastFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StandardNaastFrame.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new StandardNaastFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JMenuBar jMenuBar1;

	private JMenu jMenu1;

	private JMenu jMenu2;

	private JTabbedPane mainTabbedPane;

	private JTabbedPane memberTabbedPane;

	private MembersTable membersTable;

	private JPanel jPanel1;

	private MembersForm membersForm;
	// End of variables declaration//GEN-END:variables

}
